version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = true
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
customportalapi = true
mcwdoors = true
mutantmonsters = true
mythicmetals = true
backpacked = true
alloy_forgery = true
paladins = true
deeperdarker = true
endrem = true
betternether = true
trashcans = true
friendsandfoes = true
runes = true
minecraft = true
enderzoology = true
fwaystones = true
yigd = true
mcwtrpdoors = true
phantasm = true
adventurez = true
bosses_of_mass_destruction = true
tradingpost = true
archers = true
handcrafted = true
advancednetherite = true
ad_astra = true
armortoolsores = true
spell_engine = true
