version = 1
enableSodiumMenu = true
cloudCulling = false
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 9
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 4
includeMangroveRoots = false
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
mythicmetals = true
spelunkery = true
supplementaries = true
eternal_starlight = true
alloy_forgery = true
nomansland = true
sawmill = true
ribbits = true
friendsandfoes = true
another_furniture = true
easyanvils = true
visualworkbench = true
ecologics = true
minecraft = true
fwaystones = true
stoneworks = true
cozyhome = true
amendments = true
bosses_of_mass_destruction = true
handcrafted = true
moonlight = true
frostiful = true
moyai = true
sophisticatedbackpacks = true
treechop = true
illagerinvasion = true
disenchanting_table = true
mysticaloaktree = true
gravestones = true
