version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = false
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 4
includeMangroveRoots = false
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
fwaystones = true
mythicmetals = true
supplementaries = true
eternal_starlight = true
alloy_forgery = true
cozyhome = true
bosses_of_mass_destruction = true
ribbits = true
handcrafted = true
friendsandfoes = true
frostiful = true
moonlight = true
ecologics = true
easyanvils = true
visualworkbench = true
sophisticatedbackpacks = true
illagerinvasion = true
minecraft = true
mysticaloaktree = true
gravestones = true
